import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'landing.hero.cta.abandoned': 'FIND ABANDONED FURNITURE',
    'landing.hero.cta.share': 'SHARE YOUR FINDS',
    'landing.stooping.title': 'STOOPING & THRIFTING APP',
    'landing.stooping.subtitle': 'save the planet by hunting abandoned furnitures. earn money exploring your city in a circular economy marketplace and game.',
    'landing.comingSoon': 'Coming soon',
    'landing.pokemon.text': 'Instead of hunting Pokémons, explore and hunt abandoned furnitures and other objects. Earn money and Save them from the landfill.',
    'landing.hunt.treasures': 'Hunt abandoned treasures and sell them $$$',
    'landing.hunt.explore': 'Explore your city and earn money by sharing photos and coordinates',
    'landing.coordinates.title': 'MAKE MONEY SHARING PHOTOS AND COORDINATES OF ABANDONED STREET FINDS',
    'landing.coordinates.feature1': 'hunt furniture, electronics or treasures abandoned on the street',
    'landing.coordinates.feature2': 'share the approximate location and earn money when someone buys the exact coordinates',
    'landing.coordinates.feature3': 'turn your daily walks into an urban business opportunity',
    'landing.coordinates.buy.title': 'BUY COORDINATES AND GET BARGAINS',
    'landing.coordinates.buy.description': 'you know there is a free couch 6 miles away from you but not exactly where, buy the coordinates and get a $200 couch for $1',
    'landing.thrift.title': 'EXPLORE LOCAL CIRCULAR THRIFT STORES AND GARAGE SALES',
    'landing.thrift.feature1': 'BROWSE CATALOGS OF LOCAL THRIFT STORES, GARAGE SALES AND CIRCULAR MARKETS FROM HOME. CHAT AND NEGOTIATE',
    'landing.thrift.feature2': "VISIT ONLY THE PLACES THAT HAVE WHAT YOU'RE LOOKING FOR, SAVING TIME AND GAS",
    'landing.thrift.feature3': 'ASK THEM TO COME TO YOUR HOUSE TO COLLECT YOUR UNWANTED ITEMS INSTEAD OF THROWING THEM IN THE TRASH',
    'landing.market.title': 'CREATE YOUR OWN CIRCULAR MARKET PROFILE FREE, MAKE MONEY WITH UNWANTED STUFF AND SAVE THE PLANET',
    'landing.economy.buy': '1 BUY',
    'landing.economy.use': '2 USE',
    'landing.economy.dump': '3 DUMP',
    'landing.economy.text': 'The linear economy of buy, use and Dump has changed forever',
    'landing.footer.tagline': 'Making local circular economy Easy, fun and profitable',
    'landing.beta.title': 'GET BETA AND PROJECT UPDATES',
    'landing.beta.description': 'Be among the first to try GreenHunt',
    'landing.beta.placeholder': 'Enter your email',
    'landing.beta.button': 'GET BETA',
    'landing.beta.joining': 'Sending...',
    'landing.beta.emailExists': 'This email is already on the waitlist!',
    'landing.beta.error': 'Something went wrong. Please try again.',
    'landing.beta.success': "We've sent you the beta by email!",
    'landing.beta.invalidEmail': 'Please enter a valid email address',
    'landing.markets.discover.title': 'DISCOVER LOCAL CIRCULAR MARKETS',
    'landing.markets.discover.feature1': 'Browse garage sales, thrift stores and circular markets near you',
    'landing.markets.discover.feature2': 'Find exact locations with our interactive map',
    'landing.markets.discover.feature3': 'Discover abandoned furniture left on the street',
    'landing.markets.discover.feature4': 'Create your own circular market or garage sale',
    'landing.survey.title': 'HELP US BUILD THE FUTURE',
    'landing.survey.description': 'Share your feedback and help us create the best stooping experience',
    'landing.survey.stooper.title': 'For Stooping Enthusiasts',
    'landing.survey.manager.title': 'For Circular Market Managers',
    'landing.survey.button': 'TAKE SURVEY',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.terms': 'Terms & Conditions',
    'landing.footer.cookies': 'Cookie Policy',
    'landing.footer.madeWith': 'Made with',
    'landing.footer.forPlanet': 'for the planet',
    'landing.footer.contact': 'Contact: stooping@greenriot.net',
    'landing.ambassador.title': "Are you an Influencer?",
    'landing.ambassador.description': "If you are an influencer who shares our values and mission, let's discuss a partnership for the GreenHunt launch. Influencers who support us during this phase will become Lifetime Ambassadors, gaining access to exclusive perks like higher affiliate commissions and more",
    'landing.ambassador.button': 'Ambassadors program',
    'ambassador.dashboard': 'Ambassador Dashboard',
    'ambassador.welcome': 'Welcome',
    'ambassador.logout': 'Logout',
    'ambassador.login': 'Ambassador Login',
    'ambassador.nickname': 'Nickname',
    'ambassador.password': 'Password',
    'ambassador.loading': 'Loading...',
    'ambassador.loginBtn': 'Login',
    'ambassador.signupBtn': 'Sign Up',
    'ambassador.noAccount': "Don't have an account? Sign up",
    'ambassador.hasAccount': 'Already have an account? Login',
    'ambassador.backHome': 'Back to Home',
    'ambassador.gotStore': 'I Got a Store!',
    'ambassador.mySubmissions': 'My Store Submissions',
    'ambassador.leaderboard': 'Ambassador Leaderboard',
    'ambassador.form.title': 'Submit a New Store',
    'ambassador.form.storeName': 'Store Name',
    'ambassador.form.storeUrl': 'Website or Google Maps Profile',
    'ambassador.form.city': 'City',
    'ambassador.form.warning': 'Ask the store that signed the agreement to send us an email with the contract attached to hello@greenhunt.net. We will verify it and send commissions to the USD bank accounts configured in your profile at the end of the month.',
    'ambassador.form.submit': 'Submit Store',
    'ambassador.form.cancel': 'Cancel',
    'ambassador.form.success': 'Store submitted successfully!',
    'ambassador.form.error': 'Error submitting store',
    'ambassador.submissions.status': 'Status',
    'ambassador.submissions.pending': 'Pending Review',
    'ambassador.submissions.approved': 'Approved',
    'ambassador.submissions.rejected': 'Rejected',
    'ambassador.submissions.commission': 'Commission',
    'ambassador.submissions.submittedOn': 'Submitted on',
    'ambassador.submissions.empty': 'No submissions yet',
    'ambassador.leaderboard.rank': 'Rank',
    'ambassador.leaderboard.ambassador': 'Ambassador',
    'ambassador.leaderboard.stores': 'Stores',
    'ambassador.leaderboard.earned': 'Total Earned',
    'ambassador.leaderboard.empty': 'No ambassadors on the leaderboard yet',
    'ambassador.accountCreated': 'Ambassador account created successfully!',
    'ambassador.loginSuccess': 'Logged in successfully!',
    'ambassador.logoutSuccess': 'Logged out successfully',
    'ambassador.loginError': 'Error logging in',
    'ambassador.createError': 'Error creating account',
    'landing.tutorial.title': 'STOOPING (DISCARDED STUFF ON THE STREET)',
    'landing.tutorial.step1': 'Take photos of valuable discarded street finds. Save the planet and Make money when someone nearby unlocks the coordinates.',
    'landing.tutorial.step2': 'Buy coordinates, open Google Maps, go and get a $300 couch for $1.',
    'landing.tutorial.step3': 'Buy coordinates, open Google Maps, go and get a $300 couch for $1.',
    'landing.tutorial.disclaimer': '*It is not guaranteed that the object is still there, but the time of publication or the publisher user\'s reputation are indicators of the probability. We are integrating systems to make sure all publications are legit.',
    'landing.thrifting.title': 'Local Phygital Thrifting',
    'landing.thrifting.step1': 'Explore catalogs of local thrift stores and garage sales. Chat and negotiate.',
    'landing.thrifting.step2': 'Ask them to come to your house to collect your unwanted items instead of throwing them in the trash.',
    'landing.thrifting.step3': 'Create your own circular market on your garage for free, make money with unwanted stuff.',
    'landing.waste.title': 'WASTE MANAGEMENT',
    'landing.waste.step1': 'Share valuable item coordinates with your team with a push of a button.',
    'landing.waste.step2': 'Go to exact locations with an optimized route to pick up valuable stuff.',
    'landing.waste.step3': 'Donate it to local stores or sell it on your phygital circular market.',
    'landing.junk.title': 'JUNK REMOVAL',
    'landing.junk.step1': 'Take photos of your junk and fill the form.',
    'landing.junk.step2': 'Other users bid to pay you or to charge you for removing the junk.',
    'landing.junk.step3': 'Accept the bid you want and schedule the pick up.',
    'landing.app.title': 'Local circular economy App',
    'landing.app.subtitle': 'We make local circular collaboration between bargain hunters, valuable stuff dumpers, waste managers, junk removers, thrift stores and garage sales easy, fun and profitable',
    'landing.playPlanet.title': 'Play for the planet',
    'landing.playPlanet.subtitle': 'For fun or for money, company or individual, play for the planet and measure the impact of the treasures you saved from the landfill',
    'landing.strategic.title': 'Seeking Strategic Partners',
    'landing.strategic.subtitle': 'We are seeking innovative companies in waste management, junk removal, or the resale and antique sectors. If our vision resonates with you and you\'re ready to innovate and co-create, let\'s explore a partnership.'
  },
  es: {
    'landing.hero.cta.abandoned': 'ENCUENTRA MUEBLES ABANDONADOS',
    'landing.hero.cta.share': 'COMPARTE TUS HALLAZGOS',
    'landing.stooping.title': 'APP DE STOOPING Y THRIFTING',
    'landing.stooping.subtitle': 'salva el planeta cazando muebles abandonados. gana dinero explorando tu ciudad en un marketplace de economía circular y juego.',
    'landing.comingSoon': 'Próximamente',
    'landing.pokemon.text': 'En lugar de cazar Pokémons, explora y caza muebles y otros objetos abandonados. Gana dinero y sálvalos del vertedero.',
    'landing.hunt.treasures': 'Caza tesoros abandonados y véndelos $$$',
    'landing.hunt.explore': 'Explora tu ciudad y gana dinero compartiendo fotos y coordenadas',
    'landing.coordinates.title': 'GANA DINERO COMPARTIENDO FOTOS Y COORDENADAS DE HALLAZGOS ABANDONADOS EN LA CALLE',
    'landing.coordinates.feature1': 'caza muebles, electrónicos o tesoros abandonados en la calle',
    'landing.coordinates.feature2': 'comparte la ubicación aproximada y gana dinero cuando alguien compre las coordenadas exactas',
    'landing.coordinates.feature3': 'convierte tus paseos diarios en una oportunidad de negocio urbano',
    'landing.coordinates.buy.title': 'COMPRA COORDENADAS Y CONSIGUE GANGAS',
    'landing.coordinates.buy.description': 'sabes que hay un sofá gratis a 10 km de ti pero no exactamente dónde, compra las coordenadas y consigue un sofá de $200 por $1',
    'landing.thrift.title': 'EXPLORA TIENDAS DE SEGUNDA MANO Y MERCADILLOS CIRCULARES LOCALES',
    'landing.thrift.feature1': 'NAVEGA CATÁLOGOS DE TIENDAS DE SEGUNDA MANO, MERCADILLOS Y MERCADOS CIRCULARES DESDE CASA. CHATEA Y NEGOCIA',
    'landing.thrift.feature2': 'VISITA SOLO LOS LUGARES QUE TIENEN LO QUE BUSCAS, AHORRANDO TIEMPO Y GASOLINA',
    'landing.thrift.feature3': 'PÍDELES QUE VENGAN A TU CASA A RECOGER TUS ARTÍCULOS NO DESEADOS EN LUGAR DE TIRARLOS A LA BASURA',
    'landing.market.title': 'CREA TU PROPIO PERFIL DE MERCADO CIRCULAR GRATIS, GANA DINERO CON COSAS NO DESEADAS Y SALVA EL PLANETA',
    'landing.economy.buy': '1 COMPRAR',
    'landing.economy.use': '2 USAR',
    'landing.economy.dump': '3 TIRAR',
    'landing.economy.text': 'La economía lineal de comprar, usar y tirar ha cambiado para siempre',
    'landing.footer.tagline': 'Haciendo la economía circular local fácil, divertida y rentable',
    'landing.beta.title': 'OBTÉN LA BETA Y NOVEDADES DEL PROYECTO',
    'landing.beta.description': 'Sé de los primeros en probar GreenHunt',
    'landing.beta.placeholder': 'Introduce tu email',
    'landing.beta.button': 'GET BETA',
    'landing.beta.joining': 'Enviando...',
    'landing.beta.emailExists': '¡Este email ya está en la lista de espera!',
    'landing.beta.error': 'Algo salió mal. Por favor, inténtalo de nuevo.',
    'landing.beta.success': '¡Te hemos enviado la beta por correo electrónico!',
    'landing.beta.invalidEmail': 'Por favor, introduce una dirección de email válida',
    'landing.markets.discover.title': 'DESCUBRE MERCADOS CIRCULARES LOCALES',
    'landing.markets.discover.feature1': 'Explora mercadillos, tiendas de segunda mano y mercados circulares cerca de ti',
    'landing.markets.discover.feature2': 'Encuentra ubicaciones exactas con nuestro mapa interactivo',
    'landing.markets.discover.feature3': 'Descubre muebles abandonados en la calle',
    'landing.markets.discover.feature4': 'Crea tu propio mercado circular o mercadillo',
    'landing.survey.title': 'AYÚDANOS A CONSTRUIR EL FUTURO',
    'landing.survey.description': 'Comparte tu opinión y ayúdanos a crear la mejor experiencia de stooping',
    'landing.survey.stooper.title': 'Para Entusiastas del Stooping',
    'landing.survey.manager.title': 'Para Gestores de Mercados Circulares',
    'landing.survey.button': 'HACER ENCUESTA',
    'landing.footer.privacy': 'Política de Privacidad',
    'landing.footer.terms': 'Términos y Condiciones',
    'landing.footer.cookies': 'Política de Cookies',
    'landing.footer.madeWith': 'Hecho con',
    'landing.footer.forPlanet': 'por el planeta',
    'landing.footer.contact': 'Contacto: stooping@greenriot.net',
    'landing.ambassador.title': '¿Eres un Influencer?',
    'landing.ambassador.description': 'Si eres un influencer que comparte nuestros valores y misión, hablemos de una colaboración para el lanzamiento de GreenHunt. Los influencers que nos apoyen en esta fase se convertirán en Embajadores de por Vida, con acceso a beneficios exclusivos como comisiones de afiliado más altas y más',
    'landing.ambassador.button': 'Programa de embajadores',
    'ambassador.dashboard': 'Panel de Embajador',
    'ambassador.welcome': 'Bienvenido',
    'ambassador.logout': 'Cerrar Sesión',
    'ambassador.login': 'Inicio de Sesión de Embajador',
    'ambassador.nickname': 'Apodo',
    'ambassador.password': 'Contraseña',
    'ambassador.loading': 'Cargando...',
    'ambassador.loginBtn': 'Iniciar Sesión',
    'ambassador.signupBtn': 'Registrarse',
    'ambassador.noAccount': '¿No tienes cuenta? Regístrate',
    'ambassador.hasAccount': '¿Ya tienes cuenta? Inicia sesión',
    'ambassador.backHome': 'Volver al Inicio',
    'ambassador.gotStore': '¡Conseguí un Store!',
    'ambassador.mySubmissions': 'Mis Tiendas Enviadas',
    'ambassador.leaderboard': 'Ranking de Embajadores',
    'ambassador.form.title': 'Enviar una Nueva Tienda',
    'ambassador.form.storeName': 'Nombre de la Tienda',
    'ambassador.form.storeUrl': 'Sitio Web o Perfil de Google Maps',
    'ambassador.form.city': 'Ciudad',
    'ambassador.form.warning': 'Pídele a la tienda que firmó el acuerdo que nos envíe un email con el contrato adjunto a hello@greenhunt.net. Lo comprobaremos y enviaremos comisiones a las cuentas bancarias de USD configuradas en tu perfil a final de mes.',
    'ambassador.form.submit': 'Enviar Tienda',
    'ambassador.form.cancel': 'Cancelar',
    'ambassador.form.success': '¡Tienda enviada exitosamente!',
    'ambassador.form.error': 'Error al enviar tienda',
    'ambassador.submissions.status': 'Estado',
    'ambassador.submissions.pending': 'Pendiente de Revisión',
    'ambassador.submissions.approved': 'Aprobada',
    'ambassador.submissions.rejected': 'Rechazada',
    'ambassador.submissions.commission': 'Comisión',
    'ambassador.submissions.submittedOn': 'Enviada el',
    'ambassador.submissions.empty': 'No hay envíos todavía',
    'ambassador.leaderboard.rank': 'Posición',
    'ambassador.leaderboard.ambassador': 'Embajador',
    'ambassador.leaderboard.stores': 'Tiendas',
    'ambassador.leaderboard.earned': 'Total Ganado',
    'ambassador.leaderboard.empty': 'No hay embajadores en el ranking todavía',
    'ambassador.accountCreated': '¡Cuenta de embajador creada exitosamente!',
    'ambassador.loginSuccess': '¡Sesión iniciada exitosamente!',
    'ambassador.logoutSuccess': 'Sesión cerrada exitosamente',
    'ambassador.loginError': 'Error al iniciar sesión',
    'ambassador.createError': 'Error al crear cuenta',
    'landing.tutorial.title': 'STOOPING (COSAS DESCARTADAS EN LA CALLE)',
    'landing.tutorial.step1': 'Toma fotos de hallazgos valiosos en la calle. Salva el planeta y Gana dinero cuando alguien cercano desbloquea las coordenadas.',
    'landing.tutorial.step2': 'Compra coordenadas, abre Google Maps, ve y consigue un sofá de $300 por $1.',
    'landing.tutorial.step3': 'Compra coordenadas, abre Google Maps, ve y consigue un sofá de $300 por $1.',
    'landing.tutorial.disclaimer': '*No está garantizado que el objeto siga ahí, pero el tiempo de publicación o la reputación del usuario que publica son indicadores de probabilidad. Estamos integrando sistemas para asegurar que todas las publicaciones sean legítimas.',
    'landing.thrifting.title': 'Thrifting Phygital Local',
    'landing.thrifting.step1': 'Explora catálogos de tiendas de segunda mano y ventas de garaje locales. Chatea y negocia.',
    'landing.thrifting.step2': 'Pídeles que vengan a tu casa a recoger tus objetos no deseados en lugar de tirarlos a la basura.',
    'landing.thrifting.step3': 'Crea tu propio mercado circular en tu garaje gratis, gana dinero con cosas no deseadas.',
    'landing.waste.title': 'GESTIÓN DE RESIDUOS',
    'landing.waste.step1': 'Comparte las coordenadas de objetos valiosos con tu equipo con solo pulsar un botón.',
    'landing.waste.step2': 'Ve a ubicaciones exactas con una ruta optimizada para recoger cosas valiosas.',
    'landing.waste.step3': 'Dónalo a tiendas locales o véndelo en tu mercado circular phygital.',
    'landing.junk.title': 'RECOGIDA DE OBJETOS NO DESEADOS',
    'landing.junk.step1': 'Toma fotos de tus objetos y completa el formulario.',
    'landing.junk.step2': 'Otros usuarios pujan para pagarte o cobrarte por retirarlos.',
    'landing.junk.step3': 'Acepta la oferta que quieras y programa la recogida.',
    'landing.app.title': 'App de economía circular local',
    'landing.app.subtitle': 'Facilitamos la colaboración circular local entre cazadores de gangas, gente que tira cosas valiosas, gestores de residuos, servicios de recogida, tiendas de segunda mano y ventas de garaje de forma fácil, divertida y rentable',
    'landing.playPlanet.title': 'Juega por el planeta',
    'landing.playPlanet.subtitle': 'Por diversión o por dinero, empresa o particular, juega por el planeta y mide el impacto de los tesoros que salvaste del vertedero',
    'landing.strategic.title': 'Buscamos Socios Estratégicos',
    'landing.strategic.subtitle': 'Buscamos empresas innovadoras en gestión de residuos, recogida de trastos o el sector de reventa y antigüedades. Si nuestra visión te inspira y estás listo para innovar y co-crear, exploremos una colaboración.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'es')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
